# Generated by Django 4.2.16 on 2024-11-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['-created_at']},
        ),
    ]
