# Generated by Django 4.2.16 on 2025-02-03 10:25

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Product Name')),
                ('sku', models.CharField(blank=True, editable=False, max_length=12, unique=True, verbose_name='SKU')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Length (cm)')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Width (cm)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Height (cm)')),
                ('depth_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Depth (cm)')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Stock')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country of Origin')),
                ('product_video', models.FileField(blank=True, null=True, upload_to='products-videos/', verbose_name='Product Video')),
                ('wood_material', models.CharField(blank=True, max_length=255, null=True, verbose_name='خامة الخشب')),
                ('fabric_material', models.CharField(blank=True, max_length=255, null=True, verbose_name='خامة القماش')),
                ('upholstery_material', models.CharField(blank=True, max_length=255, null=True, verbose_name='خامة التنجيد')),
                ('warranty_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد شهور الضمان')),
                ('is_best_seller', models.BooleanField(default=False, help_text='Mark this product as a best seller.')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to hide the product from being displayed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='Category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('review', models.TextField(blank=True, null=True, verbose_name='review')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.product_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
