# Generated by Django 4.2.16 on 2024-11-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_length_cm_product_product_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='materials',
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='خامة القماش'),
        ),
        migrations.AddField(
            model_name='product',
            name='upholstery_material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='خامة التنجيد'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد شهور الضمان'),
        ),
        migrations.AddField(
            model_name='product',
            name='wood_material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='خامة الخشب'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
