# Generated by Django 4.2.16 on 2024-11-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_warranty_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد شهور الضمان'),
        ),
    ]
